// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: token_converter_contract_impl.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AElf.Contracts.TokenConverter {

  /// <summary>Holder for reflection information generated from token_converter_contract_impl.proto</summary>
  public static partial class TokenConverterContractImplReflection {

    #region Descriptor
    /// <summary>File descriptor for token_converter_contract_impl.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TokenConverterContractImplReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiN0b2tlbl9jb252ZXJ0ZXJfY29udHJhY3RfaW1wbC5wcm90bxISVG9rZW5D",
            "b252ZXJ0ZXJJbXBsGgphY3MxLnByb3RvGh50b2tlbl9jb252ZXJ0ZXJfY29u",
            "dHJhY3QucHJvdG8yjgEKGlRva2VuQ29udmVydGVyQ29udHJhY3RJbXBsGnCy",
            "zPYBOUFFbGYuQ29udHJhY3RzLlRva2VuQ29udmVydGVyLlRva2VuQ29udmVy",
            "dGVyQ29udHJhY3RTdGF0ZcrK9gEKYWNzMS5wcm90b8rK9gEedG9rZW5fY29u",
            "dmVydGVyX2NvbnRyYWN0LnByb3RvQiCqAh1BRWxmLkNvbnRyYWN0cy5Ub2tl",
            "bkNvbnZlcnRlcmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::AElf.Standards.ACS1.Acs1Reflection.Descriptor, global::AElf.Contracts.TokenConverter.TokenConverterContractReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
