// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: token_converter_contract.proto
// </auto-generated>
// Original file comments:
// *
// TokenConvert contract.
#pragma warning disable 0414, 1591
#region Designer generated code

using System.Collections.Generic;
using aelf = global::AElf.CSharp.Core;

namespace AElf.Contracts.TokenConverter {

  #region Events
  public partial class TokenBought : aelf::IEvent<TokenBought>
  {
    public global::System.Collections.Generic.IEnumerable<TokenBought> GetIndexed()
    {
      return new List<TokenBought>
      {
      new TokenBought
      {
        Symbol = Symbol
      },
      };
    }

    public TokenBought GetNonIndexed()
    {
      return new TokenBought
      {
        BoughtAmount = BoughtAmount,
        BaseAmount = BaseAmount,
        FeeAmount = FeeAmount,
      };
    }
  }

  public partial class TokenSold : aelf::IEvent<TokenSold>
  {
    public global::System.Collections.Generic.IEnumerable<TokenSold> GetIndexed()
    {
      return new List<TokenSold>
      {
      new TokenSold
      {
        Symbol = Symbol
      },
      };
    }

    public TokenSold GetNonIndexed()
    {
      return new TokenSold
      {
        SoldAmount = SoldAmount,
        BaseAmount = BaseAmount,
        FeeAmount = FeeAmount,
      };
    }
  }

  #endregion
}
#endregion

